### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by emanuc** [flathub/com.sweethome3d.Sweethome3d#1]
I have Ubuntu 20.04, when I start sweethome I have an error that requires an update of the opengl driver
My driver is up to date and functional.
```
glxinfo | grep "OpenGL version"
  OpenGL version string: 4.6.0 NVIDIA 440.44
```

```
$ flatpak run com.sweethome3d.Sweethome3d
Gtk-Message: 20:08:57.684: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:08:57.684: Failed to load module "canberra-gtk-module"
com.jogamp.opengl.GLException: J3D-Renderer-1: Error making temp context(1) current: display 0x7f7c0c14cd30, context 0x7f7c0c161a68, drawable X11OnscreenGLXDrawable[Realized true,
        Factory   jogamp.opengl.x11.glx.X11GLXDrawableFactory@66a1e7a6,
        Handle    0x6e0009b,
        Surface   JAWTWindow[0x4cd05214][JVM version: 1.8.0_202 (1.8.0 update 202)
JAWT version: 0x10004, CA_LAYER: false, isLayeredSurface false, bounds [ 0 / 0  693 x 273 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], pixelScale 1.0x1.0, shallUseOffscreenLayer false, isOffscreenLayerSurface false, attachedSurfaceLayer 0x0, windowHandle 0x6e0009b, surfaceHandle 0x6e0009b, bounds [ 0 / 0  693 x 273 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], window [0/0 693x273], pixels[scale 1.0, 1.0 -> 693x273], visible true, lockedExt false,
        config AWTGraphicsConfiguration[AWTGraphicsScreen[AWTGraphicsDevice[type .awt, connection :0.0, unitID 0, awtDevice X11GraphicsDevice[screen=0], handle 0x0], idx 0],
        chosen    GLCaps[glx vid 0x28, fbc 0xaf: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
        requested GLCaps[rgba 5/5/5/1, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
        X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x28],
        encapsulated X11GLXGraphicsConfiguration[X11GraphicsScreen[X11GraphicsDevice[type .x11, connection :99.0, unitID 0, handle 0x7f7c0c14cd30, owner true, JAWTToolkitLock[obj 0x4c4883cb, isOwner true, <3f50e26a, 5625bef1>[count 1, qsz 0, owner <J3D-Renderer-1>]]], idx 0], visualID 0x28, fbConfigID 0xaf,
        requested GLCaps[rgba 5/5/5/1, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
        chosen    GLCaps[glx vid 0x28, fbc 0xaf: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]]]],
        awtComponent com.eteks.sweethome3d.j3d.Component3DManager$ObservedCanvas3D[canvas2,0,0,693x273],
        surfaceLock <2cacb571, 6d1a3b36>[count 1, qsz 0, owner <J3D-Renderer-1>]]]
        at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:393)
        at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
        at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
        at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
        at javax.media.j3d.JoglPipeline.createNewContext(JoglPipeline.java:6411)
        at javax.media.j3d.Canvas3D.createNewContext(Canvas3D.java:4612)
        at javax.media.j3d.Canvas3D.createNewContext(Canvas3D.java:2386)
        at javax.media.j3d.Renderer.doWork(Renderer.java:881)
        at javax.media.j3d.J3dThread.run(J3dThread.java:271)
Error in Java 3D : 3 Renderer: Error creating Canvas3D graphics contextX11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 2/2, reusable (open, marked uncloseable): 0, pending (open in creation order): 2)
X11Util: Open X11 Display Connections: 2
X11Util: Open[0]: NamedX11Display[:99.0, 0x7f7c0c032340, refCount 1, unCloseable false]
X11Util: Open[1]: NamedX11Display[:99.0, 0x7f7c0c14cd30, refCount 1, unCloseable false]
```

```
$ flatpak info com.sweethome3d.Sweethome3d

Sweet Home 3D - Sweet Home 3D Interior Design Application

          ID: com.sweethome3d.Sweethome3d
         Ref: app/com.sweethome3d.Sweethome3d/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 6.2
     License: GPL-2.0-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 141,5 MB
     Runtime: org.freedesktop.Platform/x86_64/19.08
         Sdk: org.freedesktop.Sdk/x86_64/19.08

      Commit: 2121f2e5dd934cefa25526648a741045fd98ec06658f3b83748ae482ece334a2
      Parent: 17ebbdce21c46cc98aed644bb81629d2d6ed9e0ef82de21e887e496a171e7b38
     Subject: Update screenshot URLs (8b2c84ef)
        Date: 2019-10-11 08:19:31 +0000
```

**Comment by hadess** [comment]
> I have Ubuntu 20.04, when I start sweethome I have an error that requires an update of the opengl driver
> My driver is up to date and functional.

I don't know where that error comes from, but newer versions of the driver _inside Flatpak_ should get automatically installed when you run `flatpak update`.

You should be able to see which version of the NVidia driver is installed in Flatpak by running `flatpak run --command=bash com.sweethome3d.Desktop` followed by `cat /.flatpak-info`.

**Comment by emanuc** [comment]
**Thanks for checking me out.
I paste the result of the command:**

`**cat /.flatpak-info**
[Application]
name=com.sweethome3d.Sweethome3d
runtime=runtime/org.freedesktop.Platform/x86_64/19.08

[Instance]
instance-id=2834131556
instance-path=/home/emanu/.var/app/com.sweethome3d.Sweethome3d
app-path=/var/lib/flatpak/app/com.sweethome3d.Sweethome3d/x86_64/stable/2121f2e5dd934cefa25526648a741045fd98ec06658f3b83748ae482ece334a2/files
app-commit=2121f2e5dd934cefa25526648a741045fd98ec06658f3b83748ae482ece334a2
runtime-path=/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/6c6ea4e13681b61c07658c0f890beab7b27ef4dfa5567f2d2b7286d6e47a246c/files
runtime-commit=6c6ea4e13681b61c07658c0f890beab7b27ef4dfa5567f2d2b7286d6e47a246c
runtime-extensions=org.freedesktop.Platform.GL.default=8383da7a813b57b2c4456b6314c510073ee9f069248ff48d21bba0fd51dcee58;org.freedesktop.Platform.GL.nvidia-440-44=ccc8820defa6815c9ec4b3cbb44b4a71b2d414a5c9c8ecba4ecbb8c56a47387f;org.freedesktop.Platform.Locale=1e45af940bad50c5a0a9cf8ef7d402e3eb5d47b4fa1e9297184370a47f3eec0f;org.gtk.Gtk3theme.Ambiance=73fed99df212c179f776452d1eb4f49d9e8fd87ba6f8434816db2e9c6c92ea19;org.gtk.Gtk3theme.Yaru=3ef77ce7589f89040c3aeb7d07569b638c78453058ab8a73e4f7835c084e73d8;org.freedesktop.Platform.openh264=3e4c12dc2a37298a93a22cb9e5e720d69d53cacacb0fdef4cf869aa8c44a8424
branch=stable
arch=x86_64
flatpak-version=1.6.1
session-bus-proxy=true
system-bus-proxy=true

[Context]
shared=ipc;
sockets=x11;pulseaudio;
devices=dri;
filesystems=home;

[Environment]
GI_TYPELIB_PATH=/app/lib/girepository-1.0
GST_PLUGIN_SYSTEM_PATH=/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0
XDG_DATA_DIRS=/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share`

**I also started sweethome by checking the logs with "journalctl -f" I don't know if it can help, but I paste the logs:**

`feb 05 23:12:39 emanuc systemd[2471]: Started flatpak-com.sweethome3d.Sweethome3d-381622.scope.
feb 05 23:12:40 emanuc gnome-shell[2727]: Window manager warning: Window 0x5800020 sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
feb 05 23:12:40 emanuc gnome-shell[2727]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x5800007 specified for 0x5800020.
feb 05 23:12:40 emanuc gnome-shell[2727]: Window manager warning: Window 0x5800020 sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
feb 05 23:12:40 emanuc libvirtd[172646]: Failed to open file '/dev/sr0': No medium found
feb 05 23:12:40 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): CRT-0: disconnected
feb 05 23:12:40 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
feb 05 23:12:40 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0):
feb 05 23:12:40 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): SAMSUNG (DFP-0): connected
feb 05 23:12:40 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): SAMSUNG (DFP-0): Internal TMDS
feb 05 23:12:40 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): SAMSUNG (DFP-0): 340.0 MHz maximum pixel clock
feb 05 23:12:40 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0):
feb 05 23:12:40 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): Philips 190CW (DFP-1): connected
feb 05 23:12:40 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): Philips 190CW (DFP-1): Internal TMDS
feb 05 23:12:40 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): Philips 190CW (DFP-1): 330.0 MHz maximum pixel clock
feb 05 23:12:40 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0):
feb 05 23:12:42 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): CRT-0: disconnected
feb 05 23:12:42 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
feb 05 23:12:42 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0):
feb 05 23:12:42 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): SAMSUNG (DFP-0): connected
feb 05 23:12:42 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): SAMSUNG (DFP-0): Internal TMDS
feb 05 23:12:42 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): SAMSUNG (DFP-0): 340.0 MHz maximum pixel clock
feb 05 23:12:42 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0):
feb 05 23:12:42 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): Philips 190CW (DFP-1): connected
feb 05 23:12:42 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): Philips 190CW (DFP-1): Internal TMDS
feb 05 23:12:42 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0): Philips 190CW (DFP-1): 330.0 MHz maximum pixel clock
feb 05 23:12:42 emanuc /usr/lib/gdm3/gdm-x-session[2501]: (--) NVIDIA(GPU-0):
feb 05 23:12:42 emanuc org.clementine_player.Clementine.desktop[53229]: 23:12:42.866 DEBUG MainWindow:1544                  position: 110 , scrobble point: 97 , lastfm status: 0 , play count point: 97 , is local libary item: false , playlist have incremented playcount:  false
feb 05 23:12:43 emanuc libvirtd[172646]: Failed to open file '/dev/sr0': No medium found
feb 05 23:12:43 emanuc systemd[2471]: flatpak-com.sweethome3d.Sweethome3d-381622.scope: Succeeded.
`

**Comment by hadess** [comment]
You said it needed a newer driver, what made you say that? Did you try to update it if it did need a new driver?

**Comment by emanuc** [comment]
When I start sweethome3D, it gives me a warning: "Sweet Home 3D will be terminated now due to a fatal error in the 3D rendering system. Update your graphics card's DirectX / OpenGL drivers"

![Schermata del 2020-02-06 00-34-45](https://user-images.githubusercontent.com/27281121/73893191-3bd0be00-4879-11ea-9d2b-7e925738ec2e.png)

**Comment by emanuc** [comment]
I add that before it was installed by the snap store and it worked without problems, since I am migrating the packages that are available on flatpak, only with sweethome3D I have this problem.
I'll list the flatpak packages and all working

> $ flatpak list
> Name                                          Application ID                                        Version           Branch   Origin           Installation
> Vorta                                         com.borgbase.Vorta                                    v0.6.23           stable   flathub          system
> Discord                                       com.discordapp.Discord                                0.0.9             stable   flathub          system
> Flatseal                                      com.github.tchx84.Flatseal                            1.0.2             master   flatseal-origin  system
> Flatseal                                      com.github.tchx84.Flatseal                            1.2.2             stable   flathub          system
> GtkStressTesting                              com.leinardi.gst                                      0.7.1             stable   flathub          system
> GreenWithEnvy                                 com.leinardi.gwe                                      0.13.3            stable   flathub          system
> OBS Studio                                    com.obsproject.Studio                                 24.0.3-modified   stable   flathub          system
> Spotify                                       com.spotify.Client                                    1.1.10.546        stable   flathub          system
> Sweet Home 3D                                 com.sweethome3d.Sweethome3d                           6.2               stable   flathub          system
> TeamSpeak                                     com.teamspeak.TeamSpeak                               3.3.2             stable   flathub          system
> WPS Office                                    com.wps.Office                                        11.1.0.9080       stable   flathub          system
> Blender                                       org.blender.Blender                                   2.81              stable   flathub          system
> Clementine Music Player                       org.clementine_player.Clementine                      1.3.1-git         stable   flathub          system
> Piper                                         org.freedesktop.Piper                                 0.3               stable   flathub          system
> Freedesktop Platform                          org.freedesktop.Platform                              18.08.39          18.08    flathub          system
> Freedesktop Platform                          org.freedesktop.Platform                              19.08.7           19.08    flathub          system
> default                                       org.freedesktop.Platform.GL.default                                     19.08    flathub          system
> nvidia-440-44                                 org.freedesktop.Platform.GL.nvidia-440-44                               1.4      flathub          system
> ffmpeg-full                                   org.freedesktop.Platform.ffmpeg-full                                    19.08    flathub          system
> html5-codecs                                  org.freedesktop.Platform.html5-codecs                                   18.08    flathub          system
> openh264                                      org.freedesktop.Platform.openh264                                       19.08    flathub          system
> FreeFileSync                                  org.freefilesync.FreeFileSync                         10.19             stable   flathub          system
> GNU Image Manipulation Program                org.gimp.GIMP                                         2.10.14           stable   flathub          system
> Geary                                         org.gnome.Geary                                       3.34.2            stable   flathub          system
> Foto                                          org.gnome.Photos                                      3.32.0            stable   flathub          system
> GNOME Application Platform version 3.32       org.gnome.Platform                                                      3.32     flathub          system
> GNOME Application Platform version 3.34       org.gnome.Platform                                                      3.34     flathub          system
> GNOME Software Development Kit version 3.34   org.gnome.Sdk                                                           3.34     flathub          system
> Ambiance Gtk theme                            org.gtk.Gtk3theme.Ambiance                                              3.22     flathub          system
> Yaru Gtk Theme                                org.gtk.Gtk3theme.Yaru                                                  3.22     flathub          system
> Adwaita theme                                 org.kde.KStyle.Adwaita                                                  5.12     flathub          system
> Adwaita theme                                 org.kde.KStyle.Adwaita                                                  5.13     flathub          system
> KDE Application Platform                      org.kde.Platform                                                        5.12     flathub          system
> KDE Application Platform                      org.kde.Platform                                                        5.13     flathub          system
> QGnomePlatform                                org.kde.PlatformTheme.QGnomePlatform                                    5.12     flathub          system
> QGnomePlatform                                org.kde.PlatformTheme.QGnomePlatform                                    5.13     flathub          system
> QGnomePlatform-decoration                     org.kde.WaylandDecoration.QGnomePlatform-decoration                     5.12     flathub          system
> QGnomePlatform-decoration                     org.kde.WaylandDecoration.QGnomePlatform-decoration                     5.13     flathub          system
> Kdenlive                                      org.kde.kdenlive                                      19.12.1           stable   flathub          system
> Krita                                         org.kde.krita                                         4.2.8.0           stable   flathub          system
> Okular                                        org.kde.okular                                        1.9.1             stable   flathub          system
> KeePassXC                                     org.keepassxc.KeePassXC                               2.5.3             stable   flathub          system
> LibreOffice                                   org.libreoffice.LibreOffice                           6.4.0.3           stable   flathub          system
> Hardware Probe                                org.linux_hardware.hw-probe                           1.5               stable   flathub          system
> MyPaint                                       org.mypaint.MyPaint                                   1.2.1             stable   flathub          system
> Telegram Desktop                              org.telegram.desktop                                  1.9.9             stable   flathub          system
> Minitube                                      org.tordini.flavio.Minitube                                             stable   flathub          system
> VLC                                           org.videolan.VLC                                      3.0.8             stable   flathub          system
> Bluray Java menus (BDJ) plugin for VLC        org.videolan.VLC.Plugin.bdj                                             3-19.08  flathub          system
> FDK-AAC Encoding Plugin for VLC               org.videolan.VLC.Plugin.fdkaac                                          3-19.08  flathub          system
> MakeMKV plugin for VLC                        org.videolan.VLC.Plugin.makemkv                                         3-19.08  flathub          system
>

**Comment by hadess** [comment]
Try running `flatpak run --command=bash com.sweethome3d.Desktop` followed by `/app/lib/sweethome3d/SweetHome3D -Dcom.eteks.sweethome3d.j3d.useOffScreen3DView=true`

If that still crashes, try running:
`/app/lib/sweethome3d/SweetHome3D-Java3D-1_5_2`.

**Comment by hadess** [comment]
Sorry, make that:
```
JAVA_ARGS="-Dcom.eteks.sweethome3d.j3d.checkOffScreenSupport=false -Dsun.java2d.opengl=true"  /app/lib/sweethome3d/SweetHome3D
```

**Comment by hadess** [comment]
http://www.sweethome3d.com/support/forum/viewthread_thread,7269
and the Debian package's startup script have some work-arounds as well.

**Comment by emanuc** [comment]
> Try running `flatpak run --command=bash com.sweethome3d.Desktop` followed by ~`/app/lib/sweethome3d/SweetHome3D -Dcom.eteks.sweethome3d.j3d.useOffScreen3DView=true`~
> 
> If that still crashes, try running:
> `/app/lib/sweethome3d/SweetHome3D-Java3D-1_5_2`.

Thanks for your time.
With this command I managed to start sweethome3D, but is there a solution to fix it on normal startup?

> emanu@emanuc:/var/lib/flatpak$ **flatpak run --command=bash com.sweethome3d.Sweethome3d  /app/lib/sweethome3d/SweetHome3D-Java3D-1_5_2**
> Java 3D: implicit antialiasing enabled
> Gtk-Message: 11:21:13.165: Failed to load module "canberra-gtk-module"
> Gtk-Message: 11:21:13.165: Failed to load module "canberra-gtk-module"
>

**Comment by hadess** [comment]
Please try the last one I mentioned as well, using `JAVA_ARGS`

**Comment by emanuc** [comment]
Sorry. Did I run the correct command? In case it gives me an error:


emanu@emanuc:/var/lib/flatpak$ **flatpak run --command=bash com.sweethome3d.Desktop JAVA_ARGS="-Dcom.eteks.sweethome3d.j3d.checkOffScreenSupport=false -Dsun.java2d.opengl=true"  /app/lib/sweethome3d/SweetHome3D**

error: app/com.sweethome3d.Desktop/x86_64/master not installed

**Comment by hadess** [comment]
They're 2 separate commands.

```
flatpak run --command=bash com.sweethome3d.Desktop
```
And when you're at the bash prompt, inside Flatpak, run:
```
JAVA_ARGS="-Dcom.eteks.sweethome3d.j3d.checkOffScreenSupport=false -Dsun.java2d.opengl=true" /app/lib/sweethome3d/SweetHome3D
```

**Comment by emanuc** [comment]
> ```
> JAVA_ARGS="-Dcom.eteks.sweethome3d.j3d.checkOffScreenSupport=false -Dsun.java2d.opengl=true" /app/lib/sweethome3d/SweetHome3D
> ```
**flatpak run --command=bash com.sweethome3d.Desktop**
error: app/com.sweethome3d.Desktop/x86_64/master not installed


**JAVA_ARGS="-Dcom.eteks.sweethome3d.j3d.checkOffScreenSupport=false -Dsun.java2d.opengl=true" /app/lib/sweethome3d/SweetHome3D**
bash: /app/lib/sweethome3d/SweetHome3D: File o directory non esistente

**Comment by hadess** [comment]
>  error: app/com.sweethome3d.Desktop/x86_64/master not installed

If this fails, it means that sweethome 3D isn't installed using Flatpak....

**Comment by emanuc** [comment]
I'm sure it's installed using flatpak, from the flathub store.
![Schermata del 2020-02-07 14-12-52](https://user-images.githubusercontent.com/27281121/74032467-53f92800-49b4-11ea-8934-b39b75f4cc82.png)
![Schermata del 2020-02-07 14-15-02](https://user-images.githubusercontent.com/27281121/74032470-552a5500-49b4-11ea-94bf-9e1aa2479e26.png)

**emanu@emanuc:~$ ls .var/app/com.sweethome3d.Sweethome3d/**
cache  config  data
**emanu@emanuc:~$ ls /var/lib/flatpak/**
app/       appstream/ .changed   exports/   .removed/  repo/      runtime/   
emanu@emanuc:~$ ls /var/lib/flatpak/app/
com.borgbase.Vorta/               com.teamspeak.TeamSpeak/          org.gnome.Games/                  org.linux_hardware.hw-probe/
com.discordapp.Discord/           com.wps.Office/                   org.gnome.Geary/                  org.mypaint.MyPaint/
com.github.tchx84.Flatseal/       io.freetubeapp.FreeTube/          org.gnome.Photos/                 org.telegram.desktop/
com.leinardi.gst/                 org.blender.Blender/              org.kde.kdenlive/                 org.tordini.flavio.Minitube/
com.leinardi.gwe/                 org.clementine_player.Clementine/ org.kde.krita/                    org.videolan.VLC/
com.obsproject.Studio/            org.freedesktop.Piper/            org.kde.okular/                   
com.spotify.Client/               org.freefilesync.FreeFileSync/    org.keepassxc.KeePassXC/          
com.sweethome3d.Sweethome3d/      org.gimp.GIMP/                    org.libreoffice.LibreOffice/      
**emanu@emanuc:~$ ls /var/lib/flatpak/app/com.sweethome3d.Sweethome3d/**
current  x86_64

**Comment by hadess** [comment]
Sorry, my fault. It's called `com.sweethome3d.Sweethome3d` not `com.sweethome3d.Desktop` (I had an old version on my system). Please test:
`flatpak run --command=bash com.sweethome3d.Sweethome3d`
followed by:
`JAVA_ARGS="-Dcom.eteks.sweethome3d.j3d.checkOffScreenSupport=false -Dsun.java2d.opengl=true" /app/lib/sweethome3d/SweetHome3D`

(Use `exit` to exit the bash shell in Flatpak)

If that doesn't work, please test:
`flatpak run --command=bash com.sweethome3d.Sweethome3d`
followed by:
`/app/lib/sweethome3d/SweetHome3D-Java3D-1_5_2`

**Comment by emanuc** [comment]
**emanu@emanuc:~$ flatpak run --command=bash com.sweethome3d.Sweethome3d**


**emanu@emanuc:~$ JAVA_ARGS="-Dcom.eteks.sweethome3d.j3d.checkOffScreenSupport=false -Dsun.java2d.opengl=true" /app/lib/sweethome3d/SweetHome3D**

Gtk-Message: 21:02:52.574: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:02:52.575: Failed to load module "canberra-gtk-module"
com.jogamp.opengl.GLException: J3D-Renderer-1: Error making temp context(1) current: display 0x7effdc14f000, context 0x7effdc163d58, drawable X11OnscreenGLXDrawable[Realized true,
	Factory   jogamp.opengl.x11.glx.X11GLXDrawableFactory@6b588df9,
	Handle    0x80009b,
	Surface   JAWTWindow[0x207f086e][JVM version: 1.8.0_202 (1.8.0 update 202)
JAWT version: 0x10004, CA_LAYER: false, isLayeredSurface false, bounds [ 0 / 0  693 x 273 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], pixelScale 1.0x1.0, shallUseOffscreenLayer false, isOffscreenLayerSurface false, attachedSurfaceLayer 0x0, windowHandle 0x80009b, surfaceHandle 0x80009b, bounds [ 0 / 0  693 x 273 ], insets [ l 0, r 0 - t 0, b 0 - 0x0], window [0/0 693x273], pixels[scale 1.0, 1.0 -> 693x273], visible true, lockedExt false,
	config AWTGraphicsConfiguration[AWTGraphicsScreen[AWTGraphicsDevice[type .awt, connection :0.0, unitID 0, awtDevice X11GraphicsDevice[screen=0], handle 0x0], idx 0],
	chosen    GLCaps[glx vid 0x28, fbc 0xaf: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	requested GLCaps[rgba 5/5/5/1, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x28],
	encapsulated X11GLXGraphicsConfiguration[X11GraphicsScreen[X11GraphicsDevice[type .x11, connection :99.0, unitID 0, handle 0x7effdc14f000, owner true, JAWTToolkitLock[obj 0x30bbebd6, isOwner true, <8ede3e8, 27f59049>[count 1, qsz 0, owner <J3D-Renderer-1>]]], idx 0], visualID 0x28, fbConfigID 0xaf,
	requested GLCaps[rgba 5/5/5/1, opaque, accum-rgba 0/0/0/0, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]],
	chosen    GLCaps[glx vid 0x28, fbc 0xaf: rgba 8/8/8/8, opaque, accum-rgba 16/16/16/16, dp/st/ms 24/0/0, dbl, mono  , hw, GLProfile[GL4bc/GL4bc.hw], on-scr[.]]]],
	awtComponent com.eteks.sweethome3d.j3d.Component3DManager$ObservedCanvas3D[canvas2,0,0,693x273],
	surfaceLock <4a99a05e, 6ab4bb00>[count 1, qsz 0, owner <J3D-Renderer-1>]]]
	at jogamp.opengl.x11.glx.X11GLXContext.createImpl(X11GLXContext.java:393)
	at jogamp.opengl.GLContextImpl.makeCurrentWithinLock(GLContextImpl.java:765)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:648)
	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:586)
	at javax.media.j3d.JoglPipeline.createNewContext(JoglPipeline.java:6411)
	at javax.media.j3d.Canvas3D.createNewContext(Canvas3D.java:4612)
	at javax.media.j3d.Canvas3D.createNewContext(Canvas3D.java:2386)
	at javax.media.j3d.Renderer.doWork(Renderer.java:881)
	at javax.media.j3d.J3dThread.run(J3dThread.java:271)
Error in Java 3D : 3 Renderer: Error creating Canvas3D graphics contextX11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 2/2, reusable (open, marked uncloseable): 0, pending (open in creation order): 2)
X11Util: Open X11 Display Connections: 2
X11Util: Open[0]: NamedX11Display[:99.0, 0x7effdc030330, refCount 1, unCloseable false]
X11Util: Open[1]: NamedX11Display[:99.0, 0x7effdc14f000, refCount 1, unCloseable false]


**With this command, start without problems::**

**emanu@emanuc:~$ flatpak run --command=bash com.sweethome3d.Sweethome3d**

**emanu@emanuc:~$ /app/lib/sweethome3d/SweetHome3D-Java3D-1_5_2**
Java 3D: implicit antialiasing enabled
Gtk-Message: 21:04:52.540: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:04:52.540: Failed to load module "canberra-gtk-module"

**Comment by hadess** [comment]
Can you please test the new build at:
https://github.com/flathub/com.sweethome3d.Sweethome3d/pull/2#issuecomment-586633661
?

**Comment by emanuc** [comment]
Thanks for the correction, I confirm that it is now starting.
