### ISSUE TITLE
Crash when furniture is imported

### ISSUE THREAD

**Issue by MrReSc** [flathub/com.sweethome3d.Sweethome3d#30]
When trying to import furniture, the app crashes.
[hs_err_pid2.log](https://github.com/flathub/com.sweethome3d.Sweethome3d/files/6893670/hs_err_pid2.log)

**Comment by hadess** [comment]
I've reported the bug upstream:
https://sourceforge.net/p/sweethome3d/bugs/1046/

**Comment by garotosopa** [comment]
The bug 1046 has been closed upstream, suggesting using the script `SweetHome3D-Java3D-1_5_2` instead of `SweetHome3D`. Flatpak's launcher.sh already uses it with NVIDIA; is there any drawback to always using it?

**Comment by hadess** [comment]
> The bug 1046 has been closed upstream, suggesting using the script `SweetHome3D-Java3D-1_5_2` instead of `SweetHome3D`. Flatpak's launcher.sh already uses it with NVIDIA; is there any drawback to always using it?

It uses an old version of Java 3D, as the name implies. The commenter's crash must have been a different one, because there's no need to use the compatibility version to fix that crash, it's fixed in newer versions.
