### ISSUE TITLE
Hi DPI scaling

### ISSUE THREAD

**Issue by biji** [flathub/com.sweethome3d.Sweethome3d#32]
How to set scaling in flatpak?

Thanks

**Comment by hadess** [comment]
It doesn't support it. Sweet Home's binaries use the 1.8.0_202 JRE, but we would need [at least Java 9 to support hi-dpi](https://wiki.archlinux.org/title/HiDPI#Java_applications).

We would need to use compile/use a newer JRE, and replace it in Sweet Home's scripts.

**Comment by ar-lex** [comment]
@hadess actually Sweet Home 3D has it's own property to enable HiDPI - `com.eteks.sweethome3d.resolutionScale`, please see #42.

I used `GDK_SCALE` environment variable to set it in the launch script. If `GDK_SCALE` is not set the application runs unscaled. Works both in X11 and XWayland.  

`GDK_SCALE=1`: ![GDK_SCALE=1](https://user-images.githubusercontent.com/4410118/219373292-f8672c3c-9597-4aa3-a704-f7f9d2719954.png)

`GDK_SCALE=2`: ![GDK_SCALE=2](https://user-images.githubusercontent.com/4410118/219372413-6df640fd-d196-4d46-9c25-1b08ad42a346.png)

**Comment by ar-lex** [comment]
@hadess just tested, works like a charm. Thank you!

**Comment by hadess** [comment]
Let's call this fixed then, thanks!
