### ISSUE TITLE
Restore point of view does not re-selecte also the center-object 

### ISSUE THREAD

**Issue by ankostis** [flathub/com.sweethome3d.Sweethome3d#33]
When _"Aerial view centered on selection"_ is checked in preferences,
the _"3D view | Got to point of view"_ action does not land the camera to the original position,
but the end positions depends on the currently selected object, which might be different from the one when the point-of-view was stored.

I guess the correct behavior would be to restore also the selected object (when that abovementioned preference is checked).

**Comment by ankostis** [comment]
Additionally, the selected layer(s) are not restored.

**Comment by hadess** [comment]
Upstream bugs should be filed at:
https://sourceforge.net/p/sweethome3d/bugs/

We only deal with packaging/distribution bugs here.
