### ISSUE TITLE
No Latin Font is visible

### ISSUE THREAD

**Issue by Arkoprovo1996** [flathub/com.sweethome3d.Sweethome3d#36]
None of the Latin fonts are visible in the application for some reason. It is visible in the help section, but wobbles around on selecting the text. I can't figure out anything.

I deleted config files under ~/.config , ~/.java (including the fonts), and ~/.var/app/com.sweethome3d.Sweethome3d/
Nothing changed.

SweetHome 3D Version: 7.0.2
Operating System: Manjaro Linux 21.3.6
Kernel: Linux 5.15.57-2

Reference Image
![sweetHome3D Bug](https://user-images.githubusercontent.com/2836718/182429185-780b60bf-0542-4d0b-90af-a49241fe2518.png)
:

**Comment by hadess** [comment]
Sounds like a problem with the OS, the Flatpak works fine:
![image](https://user-images.githubusercontent.com/769861/182578429-a745c638-744d-4742-9861-c38b5f55d1b7.png)

**Comment by hadess** [comment]
It's most likely this problem, which is either a bug in the host, or Flatpak:
https://github.com/flatpak/flatpak/issues/3191
