### ISSUE TITLE
Flatpak runtimes reached end of life

### ISSUE THREAD

**Issue by bunnber** [flathub/com.sweethome3d.Sweethome3d#38]
Hey, 
thanks for the flatpak version of this application. 

The used runtimes (20.08) reached end-of-life and must be updated.

Kind regards!

**Comment by hadess** [comment]
That was fixed a week ago:
https://github.com/flathub/com.sweethome3d.Sweethome3d/pull/37
but the build system is broken:
https://discourse.flathub.org/t/enforcing-pull-request-workflow-and-green-ci-status-of-prs/3109/4

**Comment by hadess** [comment]
Worked around in https://github.com/flathub/com.sweethome3d.Sweethome3d/pull/39
