### ISSUE TITLE
SH3D doesn't work with system dark theme

### ISSUE THREAD

**Issue by pabloab** [flathub/com.sweethome3d.Sweethome3d#41]
I'm using SH3D 7.0.2, Flatpak 1.12.7 on a basic Pop!_OS 22.04 LTS (GNOME Shell 42.5) using dark theme.

Right now it seems SH3D is not designed to work with dark themes.

![image](https://user-images.githubusercontent.com/657836/219206979-a33f6f6e-da04-4877-a780-ac368c0fc698.png)

**Comment by pabloab** [comment]
I [already did it](https://sourceforge.net/p/sweethome3d/bugs/1181/).

Meanwhile, would be nice to disable system dark theme to permeate inside this flatpak. For some reason, I had this issue on Pop!_OS 22.04 but not on Ubuntu 20.04, where it stays white as the default SH3D. I couldn't find a `flatpak override` command to change this, nor a related permission on `flatpak info --show-permissions com.sweethome3d.Sweethome3d`.

**Comment by hadess** [comment]
> Meanwhile, would be nice to disable system dark theme to permeate inside this flatpak.

Let me know if you figure out how. I don't think there's a way to do that, as you're effectively changing the default theme, the only one that the Java runtime knows. So short of fixing Java...

**Comment by pabloab** [comment]
On both (Ubuntu 20.04 and Pop 22.04) I'm using a dark theme. Somehow on Pop the darkness permeate to SH3D and on Ubuntu no. On Ubuntu:

```sh
gsettings get org.gnome.desktop.interface gtk-theme  # Return 'Arc-Dark'. There is no prefer-dark key on 20.04.
grep "gtk-application-prefer-dark-theme" ~/.config/gtk-[34].0/settings.ini # Was 0 on both, changed to 1 on both, no effect on SH3D.
```

I was able to have SH3D dark theme on Ubuntu by installing the same dark theme as given by `gsettings get org.gnome.desktop.interface gtk-theme`, `org.gtk.Gtk3theme.Arc-Dark` runtime package. I'll check on Pop if something alike was installed. Maybe Flatpak just doesn't read on the host to give the guest its color scheme.

The problem is, it would be nice to disable dark theme just for this particular flatpak app that doesn't handle it correctly, but no to all the others.

**Comment by pabloab** [comment]
I answered myself:

```sh
flatpak override --user --env=GTK_THEME=arc-light com.sweethome3d.Sweethome3d # Disable just for this app
flatpak override --reset com.sweethome3d.Sweethome3d # To swich back to defaults
flatpak override --user --share=network com.sweethome3d.Sweethome3d # To reenable network (for plugins to work, SH3D bug 1177)
```
