### ISSUE TITLE
Version 7.2 now available

### ISSUE THREAD

**Issue by pabloab** [flathub/com.sweethome3d.Sweethome3d#51]
[SH3D v7.2 has been launched](http://www.sweethome3d.com/blog/2023/09/25/sweet_home_3d_7_2.html) with some great new features. If the build process and availability on Flathub is automatic, this issue should be closed.

**Comment by hadess** [comment]
And it's the version available at https://flathub.org/apps/com.sweethome3d.Sweethome3d already.

**Comment by pabloab** [comment]
Great! The build is generated automatically on every remote release of the project?

**Comment by hadess** [comment]
> Great! The build is generated automatically on every remote release of the project?

It's still a manual process to merge it, but a bot prepares it. See the Pull Requests tab in the future, you can subscribe to those to see the process in motion.
